/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	av1 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"
	rest "k8s.io/client-go/rest"

	"github.com/lilic/client-go-instrumented/metrics"
)

type InstrumentedAutoscalingV1Client struct {
	autoscalingClient av1.AutoscalingV1Interface
	metrics           *metrics.ClientMetrics
	disableName       bool
	disableNamespace  bool
}

func (c *InstrumentedAutoscalingV1Client) HorizontalPodAutoscalers(namespace string) av1.HorizontalPodAutoscalerInterface {
	// TODO: wrap prom metrics with currying namespace
	return newHorizontalPodAutoscalers(namespace, c.autoscalingClient.HorizontalPodAutoscalers(namespace), c.metrics, c.disableName, c.disableNamespace)
}

func NewInstrumentedAutoscalingV1Client(client av1.AutoscalingV1Interface, metrics *metrics.ClientMetrics, disableName, disableNamespace bool) *InstrumentedAutoscalingV1Client {
	return &InstrumentedAutoscalingV1Client{
		autoscalingClient: client,
		metrics:           metrics,
		disableName:       disableName,
		disableNamespace:  disableNamespace,
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *InstrumentedAutoscalingV1Client) RESTClient() rest.Interface {
	return c.autoscalingClient.RESTClient()
}
